### ISSUE TITLE
Including Examples or Documentation

### ISSUE THREAD

**Issue by MikePerreman** [ArminJo/AttinySendSerial_1Mhz_38400Bd#1]
Sorry if this is kindof basic, but im still new to this. I dont understand how to actually use this library. Is there an example that I could use?

Again sorry if this is obvious, but as there is no code completion in the arduino IDE, and I didnt see any instructions, I am really confused.

**Comment by ArminJo** [comment]
Hello Mike,
you know that it may be a big challenge to create code for an ATtiny if you only rely on code completion and instructions? 
But to help you, I created a new [repo](https://github.com/ArminJo/ATtinySerialOut) which can easily be used in the Arduino IDE and has code completion and a little example included.
So good luck for your ATtiny projects.

Best regards
Armin
